version: '3.8'

services:
  backend:
    image: scribemaster-backend-server:latest
    ports:
      - "5000:5000"
    networks:
      - app-net
    container_name: backend

  frontend:
    build:
      context: .
    ports:
      - "5173:80"
    networks:
      - app-net
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    container_name: frontend

networks:
  app-net:
    external: true